## Flipping coins

In [20]:
import pandas as pd
import numpy as np
from scipy.stats import bernoulli, binom

In [13]:
# Set the random seed to reproduce the results
np.random.seed(42)
# Simulate one coin flip with 35% chance of getting heads
coin_flip = bernoulli.rvs(p=0.35, size=1)

In [14]:
coin_flip

array([0])

In [15]:
# Simulate ten coin flips and get the number of heads
np.random.seed(42)
ten_coin_flips=bernoulli.rvs(p=0.35, size=10)

In [17]:
ten_coin_flips

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 1])

In [18]:
ten_coin_flips.sum()

4

## Using binom to flip even more coins

Previously, you simulated 10 coin flips with a 35% chance of getting heads using bernoulli.rvs().

This exercise loads the binom object from scipy.stats so you can use binom.rvs() to simulate 20 trials of 10 coin flips with a 35% chance of getting heads on each coin flip.

In [23]:
# Use the binom.rvs() function to simulate 20 trials of 10 coin flips with a 35% chance of getting heads.
draws = binom.rvs(n=10, p=0.35, size=20)

In [24]:
draws

array([4, 2, 3, 3, 3, 5, 2, 4, 4, 1, 4, 2, 1, 6, 6, 5, 3, 2, 4, 3])

## Predicting the probability of defects

Any situation with exactly two possible outcomes can be modeled with binomial random variables. For example, you could model if someone likes or dislikes a product, or if they voted or not.

Let's model whether or not a component from a supplier comes with a defect. From the thousands of components that we got from a supplier, we are going to take a sample of 50, selected randomly. The agreed and accepted defect rate is 2%.

Recall that:

* binom.pmf() calculates the probability of having exactly k heads out of n coin flips.
* binom.cdf() calculates the probability of having k heads or less out of n coin flips.
* binom.sf() calculates the probability of having more than k heads out of n coin flips.

In [27]:
# Probability of getting exactly 1 defective component
prob_one_defect = binom.pmf(k=1, n=50, p=0.02)

In [28]:
prob_one_defect

0.37160171437460954

In [29]:
# Probability of not getting any defective components
prob_no_defects = binom.pmf(k=0, n=50, p=0.02)

In [30]:
prob_no_defects

0.36416968008711675

In [31]:
# Probability of getting 2 or less defective components
prob_two_or_less_defects = binom.cdf(k=2, n=50, p=0.02)

In [32]:
prob_two_or_less_defects

0.9215722516490309

## Predicting employment status

Consider a survey about employment that contains the question "Are you employed?" It is known that 65% of respondents will answer "yes." Eight survey responses have been collected.

In [38]:
# Calculate the probability of getting exactly 5 yes responses
employment_survey_5_yes = binom.pmf(k=5, p=0.65, n=8)

In [39]:
employment_survey_5_yes

0.2785857790625

In [44]:
# Calculate the probability of getting 3 or less no responses
employment_survey_3_or_less_no = 1 -binom.cdf(k=3, n=8, p=0.65)

In [45]:
employment_survey_3_or_less_no

0.8939090951171875

In [46]:
# Calculate the probability of getting more than 3 yes responses
prob_more_than_three_yes = binom.sf(k=3, n=8, p =0.65)

In [47]:
prob_more_than_three_yes

0.8939090951171875

## Predicting burglary conviction rate

There are many situations that can be modeled with only two outcomes: success or failure. This exercise presents a situation that can be modeled with a binomial distribution and gives you the opportunity to calculate probabilities using binom.pmf(), binom.cdf(), and binom.sf().

Imagine that in your town there are many crimes, including burglaries, but only 20% of them get solved. Last week, there were 9 burglaries. Answer the following questions.

In [48]:
# What is the probability of solving 4 burglaries?
four_solved_burg = binom.pmf(k=4, n=9, p=0.2)

In [49]:
four_solved_burg

0.066060288

In [50]:
# What is the probability of solving more than 3 burglaries?
more_that_3_solved_burg = binom.sf(k=3, n=9, p=0.2)

In [51]:
more_that_3_solved_burg

0.08564172800000006

In [52]:
# What is the probability of solving 2 or 3 burglaries?
two_or_three_solved_burg = binom.pmf(k=2, n=9, p=0.2) + binom.pmf(k=3, n=9, p=0.2)

In [53]:
two_or_three_solved_burg

0.47815065600000023

In [54]:
# What is the probability of solving 1 or fewer or more than 7 burglaries?
tail_probabilities = binom.cdf(k=1, n=9, p=0.2) + binom.sf(k=7, n=9, p=0.2)

In [55]:
tail_probabilities

0.4362265599999997

In [56]:
binom.cdf(k=1, n=9, p=0.2)

0.4362076159999997

In [58]:
binom.sf(k=7, n=9, p=0.2)

1.894400000000001e-05