## Probability using Scipy

In [2]:
import numpy as np
import pandas as pd
from scipy.stats import uniform, norm, binom

In [3]:
# Minimal and maximum amount of waiting time
min_time = 0
max_time = 30

In [4]:
# Calculate probability of waiting less than 5 mins
prob_less_than_5 = uniform.cdf(5,0,30)

In [7]:
# Calculate probability of waiting less than 5 mins
prob_less_than_5 = uniform.cdf(5,min_time, max_time)

In [8]:
prob_less_than_5

0.16666666666666666

In [9]:
# Calculate probability of waiting more than 5 mins
prob_greater_than_5 = 1 - uniform.cdf(5, 0, 30)

In [11]:
# Calculate probability of waiting 10-20 mins
prob_between_10_and_20 = uniform.cdf(20, 0, 30) - uniform.cdf(10, 0, 30)

In [12]:
prob_between_10_and_20

0.3333333333333333

Assume that Amir usually works on 3 deals per week, and overall, he wins 30% of deals he works on. Each deal has a binary outcome: it's either lost, or won, so you can model his sales deals with a binomial distribution. 
We will simulate a year's worth of Amir's deals so he can better understand his performance.

In [35]:
# Simulate a single deal
np.random.seed(42)
binom.rvs(1, 0.3, size=1)

array([0])

In [36]:
# Simulate 1 week of 3 deals
np.random.seed(42)
binom.rvs(3, 0.3, size=1)

array([1])

Assume that Amir usually works on 3 deals per week, and overall, he wins 30% of deals he works on. Each deal has a binary outcome: it's either lost, or won, so you can model his sales deals with a binomial distribution. 
We will simulate a year's worth of Amir's deals so he can better understand his performance.

In [4]:
# Simulate a single deal
np.random.seed(42)
binom.rvs(1, 0.3, size=1)

array([0])

In [5]:
# Simulate 1 week of 3 deals
np.random.seed(42)
binom.rvs(3, 0.3, size=1)

array([1])